# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: PHP.PHP.8.0.TS
PackageVersion: 8.0.30
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
